### ISSUE TITLE
Typo: 'DownlodedFile' → 'DownloadedFile'

### ISSUE THREAD

**Issue by KSXGitHub** [deno-module/download#7]
https://github.com/deno-module/download/blob/0171fc29c96f3c82bc8f9a8af28516af079579e5/types.ts#L7

Remember to bump major version since it's a breaking change

**Comment by kt-12** [comment]
Sure, thank you for the catch. I'll release it in the next major release.

**Comment by bjesuiter** [comment]
I've added this fix also to https://github.com/deno-module/download/pull/8

**Comment by kt-12** [comment]
Fixed in `v2.0.0`
